version: '3'
services:
  db:
    restart: always
    image: maletq/bootcamp-mongodb
    volumes:
      - /data/bootcamp/mongodb:/data/bootcamp/mongodb
    networks:
      - back
    expose:
      - 27017
  express:
    restart: always
    image: maletq/bootcamp-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - back
  backend:
    restart: always
    image: maletq/bootcamp-backend
    environment:
      - DATABASE_URL=mongodb://db:27017
      - DATABASE_NAME=TopicstoreDb
      - HOST=0.0.0.0
      - PORT=5000
    depends_on:
      - db
    networks:
      - back
      - front
    expose: 
      - 5000
  frontend:
    restart: always
    image: maletq/bootcamp-frontend
    environment:
      - API_URI=http://backend:5000/api/topics
    ports:
      - 3000:3000
    networks:
      - front
    depends_on:
      - backend
networks:
  back:
  front: