version: '3'
services:
  db:
    restart: always
    image: "${DOCKER_USERNAME}/bootcamp-postgres:${TAG}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      - back
      - front
    expose:
      - 5432
  api:
    restart: always
    image: "${DOCKER_USERNAME}/bootcamp-words:${TAG}"
    depends_on:
      - db
    networks:
      - back
      - front
    expose: 
      - 8080
  web:
    restart: always
    image: "${DOCKER_USERNAME}/bootcamp-go:${TAG}"
    environment:
      - API_URI=http://api:8080/
    ports:
      - 8084:80
    networks:
      - front
    depends_on:
      - api
networks:
  back:
  front: