apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-products
  template:
    metadata:
      labels:
        app: ms-products
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: products-container
          image: maletq/ms-products:1.0 
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 3001 
          env:
            - name: ENV_VAR_NAME
              value: "DEVELOP_VALUE"
          resources:
            limits:
              cpu: "100m" 
              memory: "64Mi" 
            requests:
              cpu: "50m" 
              memory: "32Mi" 