apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort 
  selector:
    app: ms-frontend  
  ports:
    - protocol: TCP
      port: 3000   # puerto en el que escucha en el cluster
      targetPort: 3000  # puerto en el que escucha en el contenedor
      nodePort: 30010  # puerto en el que escucha en el host